services:
  akuwebsite:
    container_name: akuwebsite-dev
    build:
      context: .
    restart: no #unless-stopped
   # ports:
    #  - "8080"
    environment:
      - HOST=0.0.0.0
      #- PORT=8081
      - VIRTUAL_HOST=eecfin.local
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=eecfin.local 
      - LETSENCRYPT_EMAIL=admin@eecfin.com 
     # - CHOKIDAR_USEPOLLING=true
    networks:
      - nginx_proxy
    volumes:
      - ./:/app       # Mount your code from host
      - /app/node_modules   # Prevent overwriting container's node_modules
   
    

networks:
  nginx_proxy:
    external: true 
 